main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.home, name='home'),
   path('about/', views.about, name='about'),
   path('plants/', views.plants_index, name='index'),
   path('plants/<int:plant_id>/', views.plants_detail, name='detail'),
   path('plants/create/', views.PlantCreate.as_view(), name='plants_create'),
   path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='plants_update'),
   path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='plants_delete'),
   path('plants/<int:plant_id>/add_watering/', views.add_watering, name='add_watering'),
   path('plants/<int:plant_id>/assoc_insect/<int:insect_id>/', views.assoc_insect, name='assoc_insect'),
   path('plants/<int:plant_id>/unassoc_insect/<int:insect_id>/', views.unassoc_insect, name='unassoc_insect'),
   path('insects/', views.InsectList.as_view(), name='insects_index'),
   path('insects/<int:pk>/', views.InsectDetail.as_view(), name='insects_detail'),
   path('insects/create/', views.InsectCreate.as_view(), name='insects_create'),
   path('insects/<int:pk>/update/', views.InsectUpdate.as_view(), name='insects_update'),
   path('insects/<int:pk>/delete/', views.InsectDelete.as_view(), name='insects_delete'),
]

plantcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

toycollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

SESSION = (
  ('M', 'Morning'),
  ('A', 'Afternoon'),
  ('E', 'Evening'),
)
# Create your models here.
class Insect(models.Model):
  name = models.CharField(max_length=100)
  color = models.CharField(max_length=100)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('insects_detail', kwargs={'pk': self.id})

class Plant(models.Model):
    name = models.CharField(max_length=100)
    genus = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    age = models.IntegerField()
    insects = models.ManyToManyField(Insect)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
      return reverse('detail', kwargs={'plant_id': self.id})

class Watering(models.Model):
  date = models.DateField('Watering date')
  session = models.CharField(
    max_length=1,
    choices=SESSION,
    default=SESSION[0][0]
  )

  plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_session_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Watering

class WateringForm(ModelForm):
    class Meta:
        model = Watering
        fields = ['date', 'session']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Plant, Insect
from .forms import WateringForm

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
# Create your views here.
def home(request):
  return render(request, 'about.html')

def about(request):
  return render(request, 'about.html')

def plants_index(request):
  plants = Plant.objects.all()
  return render(request, 'plants/index.html', {'plants': plants})

def plants_detail(request, plant_id):
  plant = Plant.objects.get(id=plant_id)
  insects_plant_doesnt_have = Insect.objects.exclude(id__in = plant.insects.all().values_list('id'))
  watering_form = WateringForm()
  return render(request, 'plants/detail.html', {
    'plant': plant, 'watering_form': watering_form,
    'insects': insects_plant_doesnt_have
  })

def add_watering(request, plant_id):
  form = WateringForm(request.POST)
  if form.is_valid():
    new_watering = form.save(commit=False)
    new_watering.plant_id = plant_id
    new_watering.save()
  return redirect('detail', plant_id=plant_id)

def assoc_insect(request, plant_id, insect_id):
  Plant.objects.get(id=plant_id).insects.add(insect_id)
  return redirect('detail', plant_id=plant_id)

def unassoc_insect(request, plant_id, insect_id):
  Plant.objects.get(id=plant_id).insects.remove(insect_id)
  return redirect('detail', plant_id=plant_id)

class PlantCreate(CreateView):
  model = Plant
  fields = ['name', 'genus', 'species', 'description', 'age']
  success_url = '/plants/'

class PlantUpdate(UpdateView):
  model = Plant
  fields = ['name', 'genus', 'species', 'description', 'age']
  # fields = ['name', 'description', 'age']

class PlantDelete(DeleteView):
  model = Plant
  success_url = '/plants/'

class InsectList(ListView):
  model = Insect

class InsectDetail(DetailView):
  model = Insect

class InsectCreate(CreateView):
  model = Insect
  fields = '__all__'

class InsectUpdate(UpdateView):
  model = Insect
  fields = ['name', 'color']

class InsectDelete(DeleteView):
  model = Insect
  success_url = '/insects/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Plant Collector</h1>
<hr />
<p>Hire the Plant Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Plant Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'about' %}" class="left brand-logo">&nbsp;&nbsp;PlantCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'insects_create' %}">Add an Insect</a></li>
          <li><a href="{% url 'insects_index' %}">View All Insects</a></li>
          <li><a href="{% url 'plants_create' %}">Add a plant</a></li>
          <li><a href="{% url 'index' %}">View All My Plants</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Plant Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/main_app/insect_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete an Insect</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'insects_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/insect_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Insect Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ insect.name }}</span>
        <p>Color: {{ insect.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'insects_update' insect.id %}">Edit</a>
        <a href="{% url 'insects_delete' insect.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/insect_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add a lil' bug</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/insect_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Insect List</h1>

{% for insect in insect_list %}
  <a href="{% url 'insects_detail' insect.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ insect.name }}</span>
            <p>Color: {{ insect.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Plant</h1>

<h4> Are you sure you want to delete 
    <span class="teal-text">
        {{ object.name }}
    </span>?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes -- delete!" class="btn">
    <a href="{% url 'detail' plant.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add Plant</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Toy</h1>

<h4> Are you sure you want to delete 
    <span class="teal-text">
        {{ object.name }}
    </span>?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes -- delete!" class="btn">
    <a href="{% url 'detail' toy.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add Toy</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Plant Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ plant.name }}</span>
        <p>Genus: {{ plant.genus }}</p>
        <p>Species: {{ plant.species }}</p>
        <p>Description: {{ plant.description }}</p>
        <p>Age: {{ plant.age }} </p>
      </div>
      <div class="card-action">
        <a href="{% url 'plants_update' plant.id %}">Edit</a>
        <a href="{% url 'plants_delete' plant.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_watering' plant.id %}" method="POST">
      {% csrf_token %}
      {{ watering_form.as_p }}
      <input type="submit" class="btn" value="Add Watering">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Session</th></tr>
      </thead>
      <tbody>
        {% for watering in plant.watering_set.all %}
          <tr>
            <td>{{watering.date}}</td>
            <td>{{watering.get_session_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- This is all new markup to be added just above the <script> tag -->
  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ plant.name }}'s Insects</h3>
      {% if plant.insects.count %}
        {% for insect in plant.insects.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ insect.color }}">{{ insect.color }}</span> {{ insect.name }}
              </span>
            </div>
              <div class="card-action">
                <form action="{% url 'unassoc_insect' plant.id insect.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn">Remove</button>
                </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No bugs on the plant!</h5>
      {% endif %}
    </div>
    <!-- Available toys will come after this line -->
    <div class="col s6">
      <h3>Available Insects</h3>
      {% if insects.count %}
        {% for insect in insects.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ insect.color }}">{{ insect.color }}</span> {{ insect.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_insect' plant.id insect.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{plant.name}} has all the bugs on it.</h5>
      {% endif %}
    </div>
  </div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // add additional JS to initialize select below
  const selectEl = document.getElementById('id_session');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Plant Collection</h1>
{% for plant in plants %}
  <div class="card">
    <a href="{% url 'detail' plant.id %}">
    <div class="card-content">
      <span class="card-title">{{ plant.name }}</span>
      <p>Genus: {{ plant.genus }}</p>
      <p>Species: {{ plant.species }}</p>
      <p>Description: {{ plant.description }}</p>
      <p>Age: {{ plant.age }} </p>
    </div>
    </a>
  </div>
{% endfor %}
{% endblock %}